### ISSUE TITLE
Node version?

### ISSUE THREAD

**Issue by jere1862** [sjdodge123/spaceroyale.io#73]
Hi! What version of Node are you using for this project? When I try to run the server I get multiple errors then I have to clean install the necessary node modules. I am using node 6.10.1

**Comment by sjdodge123** [comment]
Hey there,

This project has the following dependencies:

- bcrypt 1.0.2
- express 4.10.2
- mysql 2.13.0
- socket.io 1.4.4
- node 5.4.1

**Comment by jere1862** [comment]
Do you think adding a package.json would be a good idea to keep track of the multiple modules included in the project?

**Comment by sjdodge123** [comment]
That's a great suggestion. We haven't had the need to pull the project onto many machines so it hasn't been a priority.
